# Generated by Django 2.2 on 2019-04-25 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField()),
                ('members', models.ManyToManyField(to='reviews.Critic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='reviews.Critic')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('img_url', models.URLField()),
                ('text', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('private', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('MOVI', 'Movies'), ('TV', 'TV'), ('MUSI', 'Music'), ('EVEN', 'Events'), ('PLAC', 'Places'), ('PROD', 'Products'), ('OTHE', 'Other')], default='OTHE', max_length=4)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Critic')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Group')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Critic')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Review')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
